WINDOW_WIDTH    = 800
WINDOW_HEIGHT   = 400
WINDOW_SIZE     = (WINDOW_WIDTH,WINDOW_HEIGHT)
WINDOW_RATIO    =  WINDOW_WIDTH/WINDOW_HEIGHT

PAN_BOX_WIDTH_MAX   = WINDOW_WIDTH*5
PAN_BOX_HEIGHT_MAX  = WINDOW_HEIGHT*5
PAN_BOX_WIDTH_MIN  = WINDOW_WIDTH
PAN_BOX_HEIGHT_MIN  = WINDOW_HEIGHT
PAN_BOX_WIDTH   = PAN_BOX_WIDTH_MAX
PAN_BOX_HEIGHT  = PAN_BOX_HEIGHT_MAX

PAN_STEP        = 100
