GAMEMAP_WIDTH= 4000
GAMEMAP_HEIGHT= 4650
GAMEMAP_SIZE    = (GAMEMAP_WIDTH,GAMEMAP_HEIGHT)

WINDOW_WIDTH    = 400
WINDOW_HEIGHT   = 800
WINDOW_SIZE     = (WINDOW_WIDTH,WINDOW_HEIGHT)
WINDOW_RATIO    =  WINDOW_WIDTH/WINDOW_HEIGHT

PAN_BOX_WIDTH   = WINDOW_WIDTH*5
PAN_BOX_HEIGHT  = WINDOW_HEIGHT*5
PAN_BOX_WIDTH_MIN  = WINDOW_WIDTH
PAN_BOX_HEIGHT_MIN  = WINDOW_HEIGHT
PAN_BOX_WIDTH_MAX   = PAN_BOX_WIDTH
PAN_BOX_HEIGHT_MAX  = PAN_BOX_HEIGHT

PAN_VEL        = 100


COLOR_COUNTRY   = [40,120,20]
COLOR_COUNTRY_SEL= [140,130,20]
COLOR_BORDER    = [60,60,100]
COLOR_SEA       = [50,50,125]

FILE_DATA_BIN   = "../Data/data.bin"
FILE_GAMEMAP    = "../Data/gamemap.png"
